// data.js — seed data for CodeGraph.
//
// This models a fictional (but internally consistent, realistically-shaped)
// open-source JavaScript ecosystem: frameworks, drivers, tooling and the
// small utility packages everything quietly depends on. Fictional names are
// used deliberately so the demo never asserts inaccurate facts about real
// packages, maintainers, or companies.

const packages = [
  { name: "torque", version: "4.2.0", description: "Batteries-included web application framework", category: "framework", downloadsPerWeek: 812000, license: "MIT" },
  { name: "torque-router", version: "4.2.0", description: "Route matching and middleware pipeline for torque", category: "framework", downloadsPerWeek: 790000, license: "MIT" },
  { name: "torque-cli", version: "3.1.4", description: "Scaffolding and dev server CLI for torque projects", category: "cli", downloadsPerWeek: 210000, license: "MIT" },
  { name: "copper-http-server", version: "2.9.1", description: "Low-level HTTP/1.1 and HTTP/2 server", category: "http", downloadsPerWeek: 1450000, license: "MIT" },
  { name: "copper-tls", version: "1.4.0", description: "TLS certificate loading and rotation helpers", category: "http", downloadsPerWeek: 1600000, license: "MIT" },
  { name: "lumen-http", version: "5.0.2", description: "Promise-based HTTP client", category: "http", downloadsPerWeek: 2100000, license: "MIT" },
  { name: "lumen-fetch-polyfill", version: "1.2.0", description: "Fetch API polyfill for older runtimes", category: "http", downloadsPerWeek: 340000, license: "MIT" },
  { name: "wick-orm", version: "6.3.0", description: "Query builder and ORM for relational databases", category: "orm", downloadsPerWeek: 560000, license: "Apache-2.0" },
  { name: "wick-migrate", version: "6.3.0", description: "Schema migration runner for wick-orm", category: "orm", downloadsPerWeek: 180000, license: "Apache-2.0" },
  { name: "wick-pg-driver", version: "6.3.0", description: "PostgreSQL driver adapter for wick-orm", category: "orm", downloadsPerWeek: 240000, license: "Apache-2.0" },
  { name: "wick-sqlite-driver", version: "6.2.1", description: "SQLite driver adapter for wick-orm", category: "orm", downloadsPerWeek: 150000, license: "Apache-2.0" },
  { name: "glint-test", version: "3.0.0", description: "Test runner and assertion library", category: "testing", downloadsPerWeek: 980000, license: "MIT" },
  { name: "glint-mock", version: "3.0.0", description: "Mocking and stub utilities for glint-test", category: "testing", downloadsPerWeek: 410000, license: "MIT" },
  { name: "glint-coverage", version: "2.4.0", description: "Code coverage reporting for glint-test", category: "testing", downloadsPerWeek: 300000, license: "MIT" },
  { name: "forge-build", version: "7.1.0", description: "Zero-config bundler for web apps", category: "build-tool", downloadsPerWeek: 720000, license: "MIT" },
  { name: "forge-minify", version: "7.1.0", description: "JS/CSS minifier plugin for forge-build", category: "build-tool", downloadsPerWeek: 500000, license: "MIT" },
  { name: "forge-watch", version: "7.0.3", description: "Filesystem watcher and rebuild trigger", category: "build-tool", downloadsPerWeek: 480000, license: "MIT" },
  { name: "cinder-cli", version: "2.2.0", description: "Framework for building command-line tools", category: "cli", downloadsPerWeek: 390000, license: "MIT" },
  { name: "cinder-prompt", version: "2.2.0", description: "Interactive CLI prompts and spinners", category: "cli", downloadsPerWeek: 610000, license: "MIT" },
  { name: "halo-ui", version: "9.0.0", description: "Accessible React-style UI component library", category: "ui", downloadsPerWeek: 430000, license: "MIT" },
  { name: "halo-icons", version: "9.0.0", description: "Icon set for halo-ui", category: "ui", downloadsPerWeek: 380000, license: "MIT" },
  { name: "halo-theme", version: "9.0.0", description: "Design tokens and theming engine for halo-ui", category: "ui", downloadsPerWeek: 300000, license: "MIT" },
  { name: "quill-auth", version: "3.5.0", description: "Session and credential management", category: "auth", downloadsPerWeek: 260000, license: "MIT" },
  { name: "quill-jwt", version: "3.5.0", description: "JWT signing and verification", category: "auth", downloadsPerWeek: 700000, license: "MIT" },
  { name: "quill-oauth", version: "2.1.0", description: "OAuth2 client flows for quill-auth", category: "auth", downloadsPerWeek: 190000, license: "MIT" },
  { name: "flicker-log", version: "8.4.0", description: "Structured logging library", category: "logging", downloadsPerWeek: 3100000, license: "MIT" },
  { name: "flicker-metrics", version: "1.6.0", description: "Metrics collection built on flicker-log", category: "logging", downloadsPerWeek: 220000, license: "MIT" },
  { name: "pact-schema", version: "4.0.0", description: "Runtime schema validation", category: "utility", downloadsPerWeek: 1900000, license: "MIT" },
  { name: "pact-types", version: "4.0.0", description: "Shared TypeScript type primitives for pact-schema", category: "utility", downloadsPerWeek: 2000000, license: "MIT" },
  { name: "nimbus-cache", version: "2.3.0", description: "In-memory and pluggable caching layer", category: "utility", downloadsPerWeek: 340000, license: "MIT" },
  { name: "nimbus-redis-driver", version: "2.3.0", description: "Redis backend adapter for nimbus-cache", category: "utility", downloadsPerWeek: 210000, license: "MIT" },
  { name: "drift-queue", version: "1.9.0", description: "Background job queue", category: "utility", downloadsPerWeek: 160000, license: "MIT" },
  { name: "drift-worker", version: "1.9.0", description: "Worker process runner for drift-queue", category: "utility", downloadsPerWeek: 140000, license: "MIT" },
  { name: "socket-pipe", version: "3.2.0", description: "WebSocket server and client", category: "http", downloadsPerWeek: 380000, license: "MIT" },
  { name: "glyph-markdown", version: "5.1.0", description: "Markdown to HTML renderer", category: "utility", downloadsPerWeek: 290000, license: "MIT" },
  { name: "glyph-slugify", version: "1.3.0", description: "URL-safe slug generator", category: "utility", downloadsPerWeek: 450000, license: "MIT" },
  { name: "tinyshim", version: "1.0.7", description: "Tiny cross-runtime object and array helpers", category: "utility", downloadsPerWeek: 4200000, license: "MIT" },
  { name: "left-field", version: "0.2.1", description: "Left-aligned fixed-width text padding", category: "utility", downloadsPerWeek: 90000, license: "MIT" },
  { name: "clockwork-cron", version: "2.0.0", description: "Cron expression scheduler", category: "utility", downloadsPerWeek: 170000, license: "MIT" },
  { name: "vellum-pdf", version: "1.5.0", description: "PDF generation from HTML/Markdown", category: "utility", downloadsPerWeek: 130000, license: "MIT" },
  { name: "atlas-geo", version: "1.1.0", description: "Geospatial distance and bounding-box utilities", category: "utility", downloadsPerWeek: 95000, license: "MIT" },
  { name: "lattice-graphql", version: "3.0.0", description: "GraphQL server built on torque", category: "framework", downloadsPerWeek: 175000, license: "MIT" },
  { name: "lattice-schema-stitch", version: "1.0.2", description: "Schema stitching for lattice-graphql", category: "framework", downloadsPerWeek: 60000, license: "MIT" },
  { name: "beacon-analytics", version: "2.1.0", description: "Event tracking client", category: "utility", downloadsPerWeek: 150000, license: "MIT" },
];

// [from, to] meaning "from DEPENDS_ON to"
const dependsOn = [
  ["torque", "copper-http-server"],
  ["torque", "torque-router"],
  ["torque", "pact-schema"],
  ["torque", "flicker-log"],
  ["torque-router", "pact-types"],
  ["torque-cli", "torque"],
  ["torque-cli", "cinder-cli"],
  ["torque-cli", "forge-build"],
  ["copper-http-server", "copper-tls"],
  ["copper-http-server", "flicker-log"],
  ["lumen-http", "copper-tls"],
  ["lumen-http", "tinyshim"],
  ["lumen-fetch-polyfill", "tinyshim"],
  ["wick-orm", "pact-schema"],
  ["wick-orm", "flicker-log"],
  ["wick-orm", "nimbus-cache"],
  ["wick-migrate", "wick-orm"],
  ["wick-migrate", "cinder-cli"],
  ["wick-pg-driver", "wick-orm"],
  ["wick-sqlite-driver", "wick-orm"],
  ["glint-test", "pact-types"],
  ["glint-test", "flicker-log"],
  ["glint-mock", "glint-test"],
  ["glint-coverage", "glint-test"],
  ["forge-build", "forge-minify"],
  ["forge-build", "forge-watch"],
  ["forge-build", "glyph-slugify"],
  ["forge-minify", "tinyshim"],
  ["forge-watch", "tinyshim"],
  ["cinder-cli", "cinder-prompt"],
  ["cinder-cli", "pact-types"],
  ["cinder-prompt", "tinyshim"],
  ["halo-ui", "halo-icons"],
  ["halo-ui", "halo-theme"],
  ["halo-ui", "pact-types"],
  ["halo-icons", "tinyshim"],
  ["halo-theme", "tinyshim"],
  ["quill-auth", "quill-jwt"],
  ["quill-auth", "flicker-log"],
  ["quill-jwt", "tinyshim"],
  ["quill-oauth", "quill-auth"],
  ["quill-oauth", "lumen-http"],
  ["flicker-metrics", "flicker-log"],
  ["pact-schema", "pact-types"],
  ["nimbus-cache", "flicker-log"],
  ["nimbus-redis-driver", "nimbus-cache"],
  ["drift-queue", "nimbus-redis-driver"],
  ["drift-queue", "flicker-log"],
  ["drift-worker", "drift-queue"],
  ["drift-worker", "flicker-log"],
  ["socket-pipe", "copper-http-server"],
  ["socket-pipe", "flicker-log"],
  ["glyph-markdown", "tinyshim"],
  ["glyph-slugify", "tinyshim"],
  ["clockwork-cron", "flicker-log"],
  ["vellum-pdf", "tinyshim"],
  ["vellum-pdf", "glyph-markdown"],
  ["atlas-geo", "tinyshim"],
  ["lattice-graphql", "pact-schema"],
  ["lattice-graphql", "torque"],
  ["lattice-schema-stitch", "lattice-graphql"],
  ["beacon-analytics", "lumen-http"],
  ["beacon-analytics", "flicker-log"],
];

const organizations = [
  { name: "Torque Foundation", type: "Foundation" },
  { name: "Copper Systems Inc", type: "Company" },
  { name: "Wick Labs", type: "Company" },
  { name: "Open Glint Collective", type: "Foundation" },
  { name: "Forge Tooling", type: "Company" },
  { name: "Halo Design Co", type: "Company" },
  { name: "Nimbus Cloud", type: "Company" },
];

const developers = [
  { name: "Rhea Okonkwo", username: "rokonkwo", bio: "Framework internals and performance" },
  { name: "Sam Delacroix", username: "sdelacroix", bio: "Routing and middleware" },
  { name: "Priya Nathan", username: "pnathan", bio: "Networking and protocol implementation" },
  { name: "Marcus Webb", username: "mwebb", bio: "TLS and security tooling" },
  { name: "Ines Farrow", username: "ifarrow", bio: "HTTP clients and polyfills" },
  { name: "Tobias Renner", username: "trenner", bio: "Database drivers" },
  { name: "Aiko Sato", username: "asato", bio: "ORM query planning" },
  { name: "Devon Marsh", username: "dmarsh", bio: "Test infrastructure" },
  { name: "Nadia Osei", username: "nosei", bio: "Coverage and reporting tooling" },
  { name: "Leo Furlan", username: "lfurlan", bio: "Build tooling and bundler internals" },
  { name: "Yara Haddad", username: "yhaddad", bio: "CLI ergonomics" },
  { name: "Connor Blake", username: "cblake", bio: "Design systems and accessibility" },
  { name: "Simone Voss", username: "svoss", bio: "Theming and design tokens" },
  { name: "Ravi Chandran", username: "rchandran", bio: "Auth and identity" },
  { name: "Elin Bergstrom", username: "ebergstrom", bio: "Token and credential handling" },
  { name: "Omar Idris", username: "oidris", bio: "Logging and observability" },
  { name: "Kate Lindqvist", username: "klindqvist", bio: "Metrics and telemetry" },
  { name: "Felix Amaro", username: "famaro", bio: "Schema validation" },
  { name: "Hana Kobayashi", username: "hkobayashi", bio: "Caching and job queues" },
  { name: "Bram Costa", username: "bcosta", bio: "WebSockets and realtime" },
  { name: "Petra Zima", username: "pzima", bio: "Small independent utility libraries" },
  { name: "Wesley Choi", username: "wchoi", bio: "Independent maintainer, core primitives" },
  { name: "Gita Rao", username: "grao", bio: "GraphQL tooling" },
  { name: "Noor Siddiqui", username: "nsiddiqui", bio: "Analytics and event tracking" },
];

// Which developer(s) maintain which package (small teams — sometimes just one person).
const maintains = {
  "torque": ["Rhea Okonkwo", "Sam Delacroix"],
  "torque-router": ["Sam Delacroix"],
  "torque-cli": ["Yara Haddad"],
  "copper-http-server": ["Priya Nathan"],
  "copper-tls": ["Marcus Webb"],
  "lumen-http": ["Ines Farrow"],
  "lumen-fetch-polyfill": ["Ines Farrow"],
  "wick-orm": ["Aiko Sato", "Tobias Renner"],
  "wick-migrate": ["Aiko Sato"],
  "wick-pg-driver": ["Tobias Renner"],
  "wick-sqlite-driver": ["Tobias Renner"],
  "glint-test": ["Devon Marsh"],
  "glint-mock": ["Devon Marsh"],
  "glint-coverage": ["Nadia Osei"],
  "forge-build": ["Leo Furlan"],
  "forge-minify": ["Leo Furlan"],
  "forge-watch": ["Leo Furlan"],
  "cinder-cli": ["Yara Haddad"],
  "cinder-prompt": ["Yara Haddad"],
  "halo-ui": ["Connor Blake", "Simone Voss"],
  "halo-icons": ["Connor Blake"],
  "halo-theme": ["Simone Voss"],
  "quill-auth": ["Ravi Chandran"],
  "quill-jwt": ["Elin Bergstrom"],
  "quill-oauth": ["Ravi Chandran"],
  "flicker-log": ["Omar Idris"],
  "flicker-metrics": ["Kate Lindqvist"],
  "pact-schema": ["Felix Amaro"],
  "pact-types": ["Felix Amaro"],
  "nimbus-cache": ["Hana Kobayashi"],
  "nimbus-redis-driver": ["Hana Kobayashi"],
  "drift-queue": ["Hana Kobayashi"],
  "drift-worker": ["Hana Kobayashi"],
  "socket-pipe": ["Bram Costa"],
  "glyph-markdown": ["Petra Zima"],
  "glyph-slugify": ["Petra Zima"],
  "tinyshim": ["Wesley Choi"],
  "left-field": ["Wesley Choi"],
  "clockwork-cron": ["Petra Zima"],
  "vellum-pdf": ["Petra Zima"],
  "atlas-geo": ["Wesley Choi"],
  "lattice-graphql": ["Gita Rao"],
  "lattice-schema-stitch": ["Gita Rao"],
  "beacon-analytics": ["Noor Siddiqui"],
};

// [developer, package, commits] — lighter-touch contributors, distinct from maintainers.
const contributesTo = [
  ["Priya Nathan", "torque", 42],
  ["Marcus Webb", "torque", 11],
  ["Devon Marsh", "torque-router", 19],
  ["Ines Farrow", "copper-http-server", 8],
  ["Tobias Renner", "wick-migrate", 15],
  ["Aiko Sato", "wick-pg-driver", 22],
  ["Nadia Osei", "glint-test", 30],
  ["Yara Haddad", "forge-build", 6],
  ["Leo Furlan", "cinder-cli", 4],
  ["Simone Voss", "halo-icons", 17],
  ["Connor Blake", "halo-theme", 9],
  ["Elin Bergstrom", "quill-auth", 13],
  ["Ravi Chandran", "quill-jwt", 7],
  ["Kate Lindqvist", "flicker-log", 25],
  ["Omar Idris", "flicker-metrics", 12],
  ["Hana Kobayashi", "drift-worker", 5],
  ["Bram Costa", "socket-pipe", 10],
  ["Petra Zima", "vellum-pdf", 3],
  ["Wesley Choi", "glyph-slugify", 6],
  ["Gita Rao", "lattice-schema-stitch", 14],
  ["Noor Siddiqui", "beacon-analytics", 9],
  ["Rhea Okonkwo", "lattice-graphql", 5],
];

// [organization, package]
const publishes = [
  ["Torque Foundation", "torque"],
  ["Torque Foundation", "torque-router"],
  ["Torque Foundation", "torque-cli"],
  ["Copper Systems Inc", "copper-http-server"],
  ["Copper Systems Inc", "copper-tls"],
  ["Wick Labs", "wick-orm"],
  ["Wick Labs", "wick-migrate"],
  ["Wick Labs", "wick-pg-driver"],
  ["Wick Labs", "wick-sqlite-driver"],
  ["Open Glint Collective", "glint-test"],
  ["Open Glint Collective", "glint-mock"],
  ["Open Glint Collective", "glint-coverage"],
  ["Forge Tooling", "forge-build"],
  ["Forge Tooling", "forge-minify"],
  ["Forge Tooling", "forge-watch"],
  ["Halo Design Co", "halo-ui"],
  ["Halo Design Co", "halo-icons"],
  ["Halo Design Co", "halo-theme"],
  ["Nimbus Cloud", "nimbus-cache"],
  ["Nimbus Cloud", "nimbus-redis-driver"],
  // tinyshim, flicker-log, pact-schema, pact-types, glyph-*, quill-*, drift-*,
  // socket-pipe, clockwork-cron, vellum-pdf, atlas-geo, lattice-*,
  // beacon-analytics, lumen-* and left-field are intentionally unpublished by
  // any organization — independently maintained, exactly like a lot of the
  // real internet's most depended-upon packages.
];

// [developer, organization]
const worksAt = [
  ["Rhea Okonkwo", "Torque Foundation"],
  ["Sam Delacroix", "Torque Foundation"],
  ["Yara Haddad", "Torque Foundation"],
  ["Priya Nathan", "Copper Systems Inc"],
  ["Marcus Webb", "Copper Systems Inc"],
  ["Aiko Sato", "Wick Labs"],
  ["Tobias Renner", "Wick Labs"],
  ["Devon Marsh", "Open Glint Collective"],
  ["Nadia Osei", "Open Glint Collective"],
  ["Leo Furlan", "Forge Tooling"],
  ["Connor Blake", "Halo Design Co"],
  ["Simone Voss", "Halo Design Co"],
  ["Hana Kobayashi", "Nimbus Cloud"],
];

module.exports = {
  packages,
  dependsOn,
  organizations,
  developers,
  maintains,
  contributesTo,
  publishes,
  worksAt,
};
